In [1]:
import pandas as pd
from glob import glob

---------------------------
### Read the single CSV file
----------------------------

In [10]:
single_filea_acc = pd.read_csv("../../data/raw/MetaMotion/MetaMotion/A-bench-heavy_MetaWear_2019-01-14T14.22.49.165_C42732BE255C_Accelerometer_12.500Hz_1.4.4.csv")

In [11]:
single_file_gyr = pd.read_csv("../../data/raw/MetaMotion/MetaMotion/A-bench-heavy_MetaWear_2019-01-14T14.22.49.165_C42732BE255C_Gyroscope_25.000Hz_1.4.4.csv")

In [12]:
# list all data in data/raw/metamotion

files = glob("../../data/raw/MetaMotion/MetaMotion/*.csv")
len(files)

187

### Extract features from file name.
- These file names have something in common, as the data do not have the lable but file names have lable and we have to get it for updating data with lable.

In [41]:
data_path = ("../../data/raw/MetaMotion/MetaMotion/")
f = files[0]

participants = f.split("-")[0].replace(data_path,"")
label = f.split("-")[1]
category = f.split("-")[2].split("_")[0].rstrip("123")

In [43]:
df = pd.read_csv(f)

df['participants'] = participants
df['label'] = label
df['category'] = category

In [44]:
df

,epoch (ms),time (01:00),elapsed (s),x-axis (g),y-axis (g),z-axis (g),participants,label,category
0,1547472577885,2019-01-14T14:29:37.885,0.00,-0.006,0.884,-0.031,C,bench,heavy
1,1547472577965,2019-01-14T14:29:37.965,0.08,-0.027,0.843,-0.053,C,bench,heavy
2,1547472578045,2019-01-14T14:29:38.045,0.16,-0.012,0.865,-0.091,C,bench,heavy
3,1547472578125,2019-01-14T14:29:38.125,0.24,-0.065,0.916,-0.040,C,bench,heavy
4,1547472578205,2019-01-14T14:29:38.205,0.32,-0.056,0.967,-0.120,C,bench,heavy
...,...,...,...,...,...,...,...,...,...
177,1547472592045,2019-01-14T14:29:52.045,14.16,0.015,1.045,0.033,C,bench,heavy
178,1547472592125,2019-01-14T14:29:52.125,14.24,0.058,0.985,-0.029,C,bench,heavy
179,1547472592205,2019-01-14T14:29:52.205,14.32,0.067,0.997,-0.029,C,bench,heavy
180,1547472592285,2019-01-14T14:29:52.285,14.40,0.037,0.994,-0.022,C,bench,heavy
181,1547472592365,2019-01-14T14:29:52.365,14.48,0.029,0.940,-0.049,C,bench,heavy

# Read all file

In [54]:
acc_df = pd.DataFrame()
gyr_df = pd.DataFrame()

acc_set = 1
gyr_set = 1

for f in files:
    participants = f.split("-")[0].replace(data_path,"")
    label = f.split("-")[1]
    category = f.split("-")[2].split("_")[0].rstrip("123")

    df = pd.read_csv(f)

    df['participants'] = participants
    df['label'] = label
    df['category'] = category

    if "Accelerometer" in f:
        df['set'] = acc_set
        acc_set += 1
        acc_df = pd.concat([acc_df, df])
        
    elif "Gyroscope" in f:
        df['set'] = gyr_set
        gyr_set += 1
        gyr_df = pd.concat([gyr_df, df])

In [57]:
acc_df[acc_df['set'] == 10]

,epoch (ms),time (01:00),elapsed (s),x-axis (g),y-axis (g),z-axis (g),participants,label,category,set
0,1548005139909,2019-01-20 18:25:39.908,0.00,0.951,0.110,0.193,E,rest,standing,10
1,1548005139989,2019-01-20 18:25:39.988,0.08,0.971,0.105,0.196,E,rest,standing,10
2,1548005140069,2019-01-20 18:25:40.068,0.16,0.954,0.081,0.196,E,rest,standing,10
3,1548005140149,2019-01-20 18:25:40.148,0.24,0.988,0.067,0.233,E,rest,standing,10
4,1548005140229,2019-01-20 18:25:40.228,0.32,0.971,0.085,0.242,E,rest,standing,10
...,...,...,...,...,...,...,...,...,...,...
493,1548005179349,2019-01-20 18:26:19.348,39.44,0.275,-0.941,0.442,E,rest,standing,10
494,1548005179429,2019-01-20 18:26:19.428,39.52,0.278,-0.939,0.435,E,rest,standing,10
495,1548005179509,2019-01-20 18:26:19.508,39.60,0.280,-0.943,0.433,E,rest,standing,10
496,1548005179589,2019-01-20 18:26:19.588,39.68,0.263,-0.968,0.414,E,rest,standing,10
497,1548005179669,2019-01-20 18:26:19.668,39.76,0.266,-0.952,0.390,E,rest,standing,10

## Working with time

In [68]:
acc_df.index = pd.to_datetime(acc_df['epoch (ms)'], unit="ms")
gyr_df.index = pd.to_datetime(gyr_df['epoch (ms)'], unit="ms")

In [72]:
acc_df.drop(['epoch (ms)', 'time (01:00)','elapsed (s)'], axis=1, inplace= True)
acc_df

,x-axis (g),y-axis (g),z-axis (g),participants,label,category,set
epoch (ms),,,,,,,
2019-01-14 13:29:37.885,-0.006,0.884,-0.031,C,bench,heavy,1
2019-01-14 13:29:37.965,-0.027,0.843,-0.053,C,bench,heavy,1
2019-01-14 13:29:38.045,-0.012,0.865,-0.091,C,bench,heavy,1
2019-01-14 13:29:38.125,-0.065,0.916,-0.040,C,bench,heavy,1
2019-01-14 13:29:38.205,-0.056,0.967,-0.120,C,bench,heavy,1
...,...,...,...,...,...,...,...
2019-01-14 13:23:01.511,-0.068,0.933,-0.345,A,bench,heavy,94
2019-01-14 13:23:01.591,-0.075,0.903,-0.349,A,bench,heavy,94
2019-01-14 13:23:01.671,-0.070,0.899,-0.361,A,bench,heavy,94
2019-01-14 13:23:01.751,-0.067,0.941,-0.365,A,bench,heavy,94
2019-01-14 13:23:01.831,-0.083,0.938,-0.366,A,bench,heavy,94

In [73]:
gyr_df.drop(['epoch (ms)', 'time (01:00)','elapsed (s)'], axis=1, inplace= True)
gyr_df

,x-axis (deg/s),y-axis (deg/s),z-axis (deg/s),participants,label,category,set
epoch (ms),,,,,,,
2019-01-15 13:53:06.457,8.720,6.951,-73.415,E,ohp,heavy,1
2019-01-15 13:53:06.497,9.634,4.756,-71.768,E,ohp,heavy,1
2019-01-15 13:53:06.537,8.232,-0.427,-57.378,E,ohp,heavy,1
2019-01-15 13:53:06.577,-2.378,6.524,-46.646,E,ohp,heavy,1
2019-01-15 13:53:06.617,-1.220,10.671,-33.780,E,ohp,heavy,1
...,...,...,...,...,...,...,...
2019-01-15 14:05:45.928,8.659,-6.280,4.146,C,row,heavy,93
2019-01-15 14:05:45.968,-2.134,6.829,-1.037,C,row,heavy,93
2019-01-15 14:05:46.008,-0.610,0.000,-0.366,C,row,heavy,93
2019-01-15 14:05:46.048,0.610,-3.049,2.256,C,row,heavy,93
2019-01-15 14:05:46.088,0.976,-5.183,2.683,C,row,heavy,93

## Create a function for all the above to wrap around

In [78]:
files = glob("../../data/raw/MetaMotion/MetaMotion/*.csv")

def read_data_from_files(files):
    acc_df = pd.DataFrame()
    gyr_df = pd.DataFrame()
    
    acc_set = 1
    gyr_set = 1
    data_path = ("../../data/raw/MetaMotion/MetaMotion/")
    f = files[0]
    for f in files:
        participants = f.split("-")[0].replace(data_path,"")
        label = f.split("-")[1]
        category = f.split("-")[2].split("_")[0].rstrip("123")
    
        df = pd.read_csv(f)
    
        df['participants'] = participants
        df['label'] = label
        df['category'] = category
    
        if "Accelerometer" in f:
            df['set'] = acc_set
            acc_set += 1
            acc_df = pd.concat([acc_df, df])
            
        elif "Gyroscope" in f:
            df['set'] = gyr_set
            gyr_set += 1
            gyr_df = pd.concat([gyr_df, df])

    acc_df.index = pd.to_datetime(acc_df['epoch (ms)'], unit="ms")
    gyr_df.index = pd.to_datetime(gyr_df['epoch (ms)'], unit="ms")

    acc_df.drop(['epoch (ms)', 'time (01:00)','elapsed (s)'], axis=1, inplace= True)
    gyr_df.drop(['epoch (ms)', 'time (01:00)','elapsed (s)'], axis=1, inplace= True)

    return acc_df, gyr_df

In [80]:
acc_df, gyr_df = read_data_from_files(files)

In [81]:
acc_df.head()

,x-axis (g),y-axis (g),z-axis (g),participants,label,category,set
epoch (ms),,,,,,,
2019-01-14 13:29:37.885,-0.006,0.884,-0.031,C,bench,heavy,1
2019-01-14 13:29:37.965,-0.027,0.843,-0.053,C,bench,heavy,1
2019-01-14 13:29:38.045,-0.012,0.865,-0.091,C,bench,heavy,1
2019-01-14 13:29:38.125,-0.065,0.916,-0.040,C,bench,heavy,1
2019-01-14 13:29:38.205,-0.056,0.967,-0.120,C,bench,heavy,1

In [94]:
## Merge the 2 data fram to one

data_merged = pd.concat([acc_df.iloc[:, :3],gyr_df], axis=1)
data_merged.columns = [
    "acc_x","acc_y","acc_z",
    "gyr_x","gyr_y", "gyr_z",
    "participants", "label", "Category", "set"]

AS there are 2 sensors accelorometer is running 0.04 second and gyroscope on 0.08 seconds hence the diffrence in the measurements and the value they are providing

- Understanding hertz and changing the series of the frequency
- refer offset data in pandas documents
- it only works in timeseries data set hence we update the index with time stamp
- use resmaple

In [95]:
#we will be using the below function and applying it to entire df
data_merged[:1000].resample(rule="200ms").mean(numeric_only=True)

,acc_x,acc_y,acc_z,gyr_x,gyr_y,gyr_z,set
epoch (ms),,,,,,,
2019-01-11 15:08:04.800,NaN,NaN,NaN,-9.69550,-1.7985,4.5735,69.0
2019-01-11 15:08:05.000,NaN,NaN,NaN,-2.01220,-0.4270,-1.6218,69.0
2019-01-11 15:08:05.200,0.013500,0.977000,-0.071000,-1.89040,2.4392,0.9388,69.0
2019-01-11 15:08:05.400,-0.001500,0.970500,-0.079500,-1.68260,-0.8904,2.1708,69.0
2019-01-11 15:08:05.600,0.001333,0.971667,-0.064333,2.56080,-0.2560,-1.4146,69.0
...,...,...,...,...,...,...,...
2019-01-11 15:10:21.600,-0.174000,1.092667,-0.153333,-4.96360,-16.4026,21.9026,59.0
2019-01-11 15:10:21.800,-0.219500,1.402500,-0.109000,-7.52440,18.6706,-22.6828,59.0
2019-01-11 15:10:22.000,-0.192000,0.871667,-0.155667,2.60980,8.7070,-14.8658,59.0
2019-01-11 15:10:22.200,-0.227000,0.891000,-0.170000,5.39020,4.0000,-0.3780,59.0
2019-01-11 15:10:22.400,-0.225500,0.919500,-0.205500,6.34125,0.5795,9.9085,59.0

In [99]:
sampling = {
    'acc_x':"mean", 'acc_y':"mean", 'acc_z':"mean", 'gyr_x':"mean", 'gyr_y':"mean", 'gyr_z':"mean", 
     'participants':"last", 'label':"last", 'Category':"last", 'set':"last"
}
data_merged[:1000].resample(rule="200ms").apply(sampling)

,acc_x,acc_y,acc_z,gyr_x,gyr_y,gyr_z,participants,label,Category,set
epoch (ms),,,,,,,,,,
2019-01-11 15:08:04.800,NaN,NaN,NaN,-9.69550,-1.7985,4.5735,B,bench,heavy,69.0
2019-01-11 15:08:05.000,NaN,NaN,NaN,-2.01220,-0.4270,-1.6218,B,bench,heavy,69.0
2019-01-11 15:08:05.200,0.013500,0.977000,-0.071000,-1.89040,2.4392,0.9388,B,bench,heavy,69.0
2019-01-11 15:08:05.400,-0.001500,0.970500,-0.079500,-1.68260,-0.8904,2.1708,B,bench,heavy,69.0
2019-01-11 15:08:05.600,0.001333,0.971667,-0.064333,2.56080,-0.2560,-1.4146,B,bench,heavy,69.0
...,...,...,...,...,...,...,...,...,...,...
2019-01-11 15:10:21.600,-0.174000,1.092667,-0.153333,-4.96360,-16.4026,21.9026,A,bench,heavy,59.0
2019-01-11 15:10:21.800,-0.219500,1.402500,-0.109000,-7.52440,18.6706,-22.6828,A,bench,heavy,59.0
2019-01-11 15:10:22.000,-0.192000,0.871667,-0.155667,2.60980,8.7070,-14.8658,A,bench,heavy,59.0
2019-01-11 15:10:22.200,-0.227000,0.891000,-0.170000,5.39020,4.0000,-0.3780,A,bench,heavy,59.0
2019-01-11 15:10:22.400,-0.225500,0.919500,-0.205500,6.34125,0.5795,9.9085,A,bench,heavy,59.0

In [102]:
# Spliting data on bases of day to reduce the unwanted data and save pc

days = [g for n, g in data_merged.groupby(pd.Grouper(freq="D"))]
data_resampled = pd.concat([df.resample(rule="200ms").apply(sampling).dropna() for df in days])
data_resampled['set'] = data_resampled['set'].astype("int")

data_resampled.info()

<class 'pandas.core.frame.DataFrame'>
DatetimeIndex: 9009 entries, 2019-01-11 15:08:05.200000 to 2019-01-20 17:33:27.800000
Data columns (total 10 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   acc_x         9009 non-null   float64
 1   acc_y         9009 non-null   float64
 2   acc_z         9009 non-null   float64
 3   gyr_x         9009 non-null   float64
 4   gyr_y         9009 non-null   float64
 5   gyr_z         9009 non-null   float64
 6   participants  9009 non-null   object
 7   label         9009 non-null   object
 8   Category      9009 non-null   object
 9   set           9009 non-null   int64
dtypes: float64(6), int64(1), object(3)
memory usage: 774.2+ KB

In [103]:
data_resampled.to_pickle("../../data/interim/01_data_processed.pkl")